# Generated by Django 3.0.6 on 2020-05-19 06:17

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Hotel',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.TextField(max_length=100)),
                ('district', models.TextField(max_length=100)),
                ('capacity', models.TextField(max_length=100)),
            ],
        ),
    ]
