# Generated by Django 3.0.6 on 2020-05-27 13:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bookingsite', '0002_customer'),
    ]

    operations = [
        migrations.AddField(
            model_name='customer',
            name='hotel_name',
            field=models.TextField(default='', max_length=100),
        ),
    ]
