# Generated by Django 3.0.6 on 2020-06-02 15:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bookingsite', '0004_auto_20200527_2124'),
    ]

    operations = [
        migrations.AlterField(
            model_name='customer',
            name='checkinday',
            field=models.TextField(default='', max_length=100),
        ),
        migrations.AlterField(
            model_name='customer',
            name='checkoutday',
            field=models.TextField(default='', max_length=100),
        ),
        migrations.AlterField(
            model_name='customer',
            name='current_address',
            field=models.TextField(default='', max_length=100),
        ),
        migrations.AlterField(
            model_name='customer',
            name='email',
            field=models.TextField(default='', max_length=100),
        ),
        migrations.AlterField(
            model_name='customer',
            name='hotel_name',
            field=models.TextField(default='', max_length=100),
        ),
        migrations.AlterField(
            model_name='customer',
            name='id_number',
            field=models.TextField(default='', max_length=100),
        ),
        migrations.AlterField(
            model_name='customer',
            name='name',
            field=models.TextField(default='', max_length=100),
        ),
        migrations.AlterField(
            model_name='customer',
            name='people',
            field=models.TextField(default='', max_length=100),
        ),
        migrations.AlterField(
            model_name='customer',
            name='phone',
            field=models.TextField(default='', max_length=100),
        ),
        migrations.AlterField(
            model_name='customer',
            name='room',
            field=models.TextField(default='', max_length=100),
        ),
    ]
