# Generated by Django 3.0.6 on 2020-07-12 15:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bookingsite', '0005_auto_20200602_2215'),
    ]

    operations = [
        migrations.AddField(
            model_name='hotel',
            name='description',
            field=models.TextField(default='', max_length=100),
        ),
    ]
