# Generated by Django 3.0.6 on 2020-07-12 16:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bookingsite', '0007_auto_20200712_2339'),
    ]

    operations = [
        migrations.AddField(
            model_name='hotel',
            name='image',
            field=models.ImageField(blank=True, null=True, upload_to=''),
        ),
    ]
